'use client';
import { useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import type { Vehicle } from '@/lib/types';

const options=['Ar-condicionado','Direção elétrica','Vidros elétricos','Travas elétricas','Multimídia','Bluetooth','Câmera de ré','Sensor de estacionamento','Bancos em couro','Airbags','ABS','Controle de estabilidade','Piloto automático'];
type Editable=Record<string,string|number|undefined>;
export function AdminVehicleForm({vehicle}:{vehicle?:Vehicle}){
 const [images,setImages]=useState<File[]>([]);const [busy,setBusy]=useState(false);const router=useRouter();const values=vehicle as unknown as Editable;
 const field=(name:string,label:string,type='text')=><label>{label}<input name={name} type={type} required={['brand','model','year','model_year','price'].includes(name)} defaultValue={values?.[name]??''}/></label>;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),db=createClient(),brand=String(f.get('brand')),model=String(f.get('model'));
  const data={slug:`${brand}-${model}-${f.get('year')}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''),brand,model,version:String(f.get('version')||'')||null,year:Number(f.get('year')),model_year:Number(f.get('model_year')),price:Number(f.get('price')),mileage:Number(f.get('mileage'))||null,transmission:String(f.get('transmission')||'')||null,fuel:String(f.get('fuel')||'')||null,color:String(f.get('color')||'')||null,doors:Number(f.get('doors'))||null,plate_end:String(f.get('plate_end')||'')||null,description:String(f.get('description')||'')||null,features:options.filter(x=>f.get(`feature-${x}`)==='on'),status:String(f.get('status')) as Vehicle['status'],featured:f.get('featured')==='on',show_when_sold:f.get('show_when_sold')==='on'};
  let id=vehicle?.id;if(id){const{error}=await db.from('vehicles').update(data).eq('id',id);if(error){alert(error.message);setBusy(false);return}}else{const{data:created,error}=await db.from('vehicles').insert(data).select('id').single();if(error||!created){alert(error?.message||'Não foi possível salvar');setBusy(false);return}id=created.id}
  if(id&&images.length){const rows=[];for(const file of images){const path=`${id}/${crypto.randomUUID()}-${file.name}`;const{error}=await db.storage.from('vehicle-images').upload(path,file);if(!error){const{data:url}=db.storage.from('vehicle-images').getPublicUrl(path);rows.push({vehicle_id:id,url:url.publicUrl,position:rows.length})}}if(rows.length){await db.from('vehicle_images').insert(rows);await db.from('vehicles').update({cover_image:rows[0].url}).eq('id',id)}}
  router.push('/admin/veiculos');router.refresh();
 }
 return <form className="form-card" onSubmit={submit}><div className="form-fields">{field('brand','Marca')}{field('model','Modelo')}{field('version','Versão')}{field('year','Ano fabricação','number')}{field('model_year','Ano modelo','number')}{field('price','Preço','number')}{field('mileage','Quilometragem','number')}<label>Câmbio<select name="transmission" defaultValue={vehicle?.transmission||''}><option value="">Selecione</option><option>Manual</option><option>Automático</option><option>Automatizado</option></select></label><label>Combustível<select name="fuel" defaultValue={vehicle?.fuel||''}><option value="">Selecione</option><option>Flex</option><option>Gasolina</option><option>Etanol</option><option>Diesel</option><option>Elétrico</option><option>Híbrido</option></select></label>{field('color','Cor')}{field('doors','Portas','number')}{field('plate_end','Final da placa')}<label>Status<select name="status" defaultValue={vehicle?.status||'available'}><option value="available">Disponível</option><option value="reserved">Reservado</option><option value="sold">Vendido</option></select></label><label className="full">Descrição<textarea name="description" defaultValue={vehicle?.description||''}/></label><label className="full">Fotos do veículo<input type="file" accept="image/*" multiple onChange={e=>setImages(Array.from(e.target.files||[]))}/><small>{images.length?`${images.length} foto(s) selecionada(s)`:vehicle?.cover_image?'A capa atual será mantida se não enviar novas fotos.':'Selecione as imagens para o veículo.'}</small></label><div className="full"><b>Itens e opcionais</b><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:8,marginTop:10}}>{options.map(x=><label key={x} style={{display:'flex',gap:7,alignItems:'center'}}><input type="checkbox" name={`feature-${x}`} defaultChecked={vehicle?.features?.includes(x)}/>{x}</label>)}</div></div><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" name="featured" defaultChecked={vehicle?.featured}/> Exibir como destaque na home</label><label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" name="show_when_sold" defaultChecked={vehicle?.show_when_sold}/> Exibir se vendido</label></div><button disabled={busy} className="btn" type="submit">{busy?'Salvando…':'Salvar veículo'}</button></form>;
}
